server:
  port: 8080
mybatis:
  mapper-locations:
    #  - classpath: mapping/*.xml
    - classpath:mapping/*.xml
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.2.102:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    url: jdbc:mysql://10.10.3.128:3306/springcloud?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  application:
    name: microcloud-provider-product

eureka:
  client: #客户端进行eureka注册配置
    service-url:
#      defaultZone: http://admin:admin@127.0.0.1:7001/eureka
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
  instance:
    instance-id: microcloud-provider-product
    prefer-ip-address: true #将ip注册到eureka上，如果不配置将显示机器的主机名
    lease-renewal-interval-in-seconds: 30 #设置心跳的时间间隔（默认是30秒）
    lease-expiration-duration-in-seconds: 90 #距离上次发送心跳之后等待下一次发送心跳的间隔时间，如果超过了此时间间隔，则认为该微服务已经宕机（默认90秒）

info:
  app.name: microcloud-provider-product
  company.name: com.gecx
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
#  security:
#    user:
#      name: admin
#      password: 123456
#      roles:
#      - USER
logging:
  level:
    com.gecx.mapper: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'
