server:
  port: 9501

eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka
#    register-with-eureka: false
    instance:
      instance-id: microcloud-zuul-gateway
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 2 # 设置心跳的时间间隔（默认是30秒）
      lease-expiration-duration-in-seconds: 5 # 如果现在超过了5秒的间隔（默认是90秒）

spring:
  application:
    name:  microcloud-zuul-gateway
#zuul:
#  routes:
#    microcloud-provider-users:  /users-proxy/**
#  ignored-services:
#    "*"

zuul:
  routes:
    users:
      path: /users-proxy/**
      serviceId: microcloud-provider-users
    users2:
      path: /users2-proxy/**
      url: http://localhost:8090/
    product:
      path: /product-proxy/**
      serviceId: microcloud-provider-product
  ignored-services:
    "*"   #忽略掉用户服务的名称
  prefix: /enjoy-api