server:
  port: 9101
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@eureka1:7001/eureka,http://admin:admin@eureka2:7002/eureka,http://admin:admin@eureka3:7003/eureka

turbine:
  app-config: MICROCLOUD-PROVIDER-PRODUCT,MICROCLOUD-PROVIDER-USERS
  cluster-name-expression: new String("default")
